repos:
- repo: https://github.com/python/black
  rev: "24.4.0"
  hooks:
  - id: black
    language_version: python3.12

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: "v1.7.1"
  hooks:
  - id: mypy
    language_version: python3.12
    args: [--ignore-missing-imports, --disallow-untyped-defs]
    exclude: tests/|migrations/
    additional_dependencies:
          [
            celery,
            dj-database-url,
            django-allauth,
            django-browser-reload,
            django-celery-beat,
            django-debug-toolbar,
            django-filter,
            django-htmx,
            django-model-utils,
            django-stubs==4.2.7,
            django-tailwind,
            Django,
            djangorestframework-stubs==3.14.5,
            djangorestframework,
            gunicorn,
            psycopg2-binary,
            python-dotenv,
            requests,
            sentry-sdk,
            whitenoise
          ]

- repo: https://github.com/PyCQA/isort
  rev: 5.13.1
  hooks:
  -   id: isort

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-merge-conflict
    language_version: "python3"
  - id: debug-statements
    language_version: "python3"
  - id: end-of-file-fixer
    language_version: "python3"
  - id: trailing-whitespace
    language_version: "python3"

- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    language_version: "python3"
    additional_dependencies:
      - flake8-bugbear
      - flake8-builtins
      - flake8-comprehensions
      - flake8-print
      - flake8-tidy-imports
    exclude: migrations

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: python-check-mock-methods
  - id: python-no-log-warn
