repos:
- repo: https://github.com/python/black
  rev: "22.6.0"
  hooks:
  - id: black
    language_version: python3.10

- repo: https://github.com/PyCQA/isort
  rev: v5.10.1
  hooks:
  -   id: isort

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-merge-conflict
    language_version: "python3"
  - id: debug-statements
    language_version: "python3"
  - id: end-of-file-fixer
    language_version: "python3"
  - id: trailing-whitespace
    language_version: "python3"

- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    language_version: "python3"
    additional_dependencies:
      - flake8-bugbear
      - flake8-builtins
      - flake8-comprehensions
      - flake8-print
      - flake8-tidy-imports
    exclude: migrations

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.9.0
  hooks:
  - id: python-check-mock-methods
  - id: python-no-log-warn
