repos:
- repo: https://github.com/python/black
  rev: "19.10b0"
  hooks:
  - id: black
    language_version: python3.8

- repo: https://github.com/asottile/seed-isort-config
  rev: v1.9.4
  hooks:
  - id: seed-isort-config

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
  -   id: isort

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: check-merge-conflict
    language_version: "python3"
  - id: debug-statements
    language_version: "python3"
  - id: end-of-file-fixer
    language_version: "python3"
  - id: trailing-whitespace
    language_version: "python3"

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
    language_version: "python3"
    additional_dependencies:
      - flake8-bugbear==18.2.0
      - flake8-builtins
      - flake8-comprehensions
      - flake8-print
      - flake8-tidy-imports
    exclude: migrations

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.3.0
  hooks:
  - id: python-check-mock-methods
  - id: python-no-log-warn
