version: '3'

volumes:
  database:
    external: false

services:
  database:
    image: postgres:13.3
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: dev_web_start
    entrypoint: /home/appuser/docker-entrypoint.sh
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:password@database:5432/postgres
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - VSCODE_DEBUGGER=True
      - PTVSD_PORT=5678
    restart: on-failure
    volumes:
      - .:/home/appuser/src
    expose:
      - "5678"
    ports:
      - "8000:8000"
      - "5678:5678"
    links:
      - database:database
      - redis:redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: dev_worker_start
    entrypoint: /home/appuser/docker-entrypoint.sh
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:password@database:5432/postgres
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - VSCODE_DEBUGGER=True
      - PTVSD_PORT=5678
    volumes:
      - .:/home/appuser/src
    links:
      - database:database
      - redis:redis
