[tool.poetry]
name = "django-project-template"
version = "0.3.0"
description = ""
authors = ["Raúl Negrón <raul.esteban.negron@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
Django = "3.2.14"
djangorestframework = "3.13.1"
django-model-utils = "4.2.0"
django-cors-headers = "3.13.0"
django-extensions = "3.2.0"
dj-database-url = "0.5.0"
psycopg2-binary = "2.9.3"
django-filter = "22.1"
dj-rest-auth = "2.2.4"
gunicorn = "20.1.0"
python-dotenv = "0.20.0"
django-allauth = "0.51.0"
argon2-cffi = "21.3.0"
sentry-sdk = "1.6.0"
whitenoise = "6.2.0"
celery = "5.2.7"
django-celery-beat = "2.3.0"
requests = "2.28.1"
redis = "4.3.4"

[tool.poetry.dev-dependencies]
black = "22.6.0"
django-debug-toolbar = "3.5.0"
isort = "5.10.1"
pre-commit = "2.19.0"
pytest = "7.1.2"
pytest-django = "4.5.2"
factory-boy = "3.2.1"
flake8 = "4.0.1"

[tool.black]
line-length = 88
target-version = ['py39']
exclude = '(\.eggs|\.git|\.mypy_cache|\.venv|_build|build|dist|.*\/migrations\/.*)'

[build-system]
requires = ["poetry_core>=1.1.0"]
build-backend = "poetry.core.masonry.api"
