[tool.poetry]
name = "django-project-template"
version = "0.1.0"
description = ""
authors = ["Raúl Negrón <raul.esteban.negron@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
django = "<3.0"
djangorestframework = "^3.11.0"
django-model-utils = "^4.0.0"
django-cors-headers = "3.3.0"
django-extensions = "3.0.9"
dj-database-url = "^0.5.0"
psycopg2-binary = "^2.8.5"
django-filter = "^2.2.0"
dj-rest-auth = "^1.0.7"
gunicorn = "^20.0.4"
python-dotenv = "^0.13.0"
django-allauth = "^0.42.0"
argon2-cffi = "^20.1.0"
sentry-sdk = "0.17.8"
whitenoise = "^5.1.0"
pre-commit = "^2.4.0"
celery = "5.0.0"
django-celery-beat = "^2.0.0"

[tool.poetry.dev-dependencies]
black = "^21.4b2"
django-debug-toolbar = "^2.2"
isort = "^5.1.2"
pre-commit = "^2.2.0"
pytest-django = "^3.9.0"
factory-boy = "^2.12.0"
flake8 = "^3.7.9"
Werkzeug = "^1.0.1"
ptvsd = "^4.3.2"

[tool.black]
line-length = 88
target-version = ['py38']
exclude = '(\.eggs|\.git|\.mypy_cache|\.venv|_build|build|dist|.*\/migrations\/.*)'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
