[tool.poetry]
name = "django-project-template"
version = "0.2.0"
description = ""
authors = ["Raúl Negrón <raul.esteban.negron@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
Django = "3.2.5"
djangorestframework = "3.12.4"
django-model-utils = "4.1.1"
django-cors-headers = "3.7.0"
django-extensions = "3.1.3"
dj-database-url = "0.5.0"
psycopg2-binary = "2.9.1"
django-filter = "2.4.0"
dj-rest-auth = "2.1.9"
gunicorn = "20.1.0"
python-dotenv = "0.18.0"
django-allauth = "0.45.0"
argon2-cffi = "20.1.0"
sentry-sdk = "1.3.0"
whitenoise = "5.2.0"
pre-commit = "2.13.0"
celery = "5.2.3"
django-celery-beat = "2.2.1"
requests = "2.26.0"

[tool.poetry.dev-dependencies]
black = "21.6b0"
django-debug-toolbar = "3.2.1"
isort = "5.9.2"
pre-commit = "2.13.0"
pytest-django = "4.4.0"
factory-boy = "3.2.0"
flake8 = "3.9.2"
Werkzeug = "2.0.1"
ptvsd = "4.3.2"

[tool.black]
line-length = 88
target-version = ['py39']
exclude = '(\.eggs|\.git|\.mypy_cache|\.venv|_build|build|dist|.*\/migrations\/.*)'

[build-system]
requires = ["poetry_core>=1.1.0"]
build-backend = "poetry.core.masonry.api"
